// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessTracker.Data;

#nullable disable

namespace ProcessTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260921202813_ExhaustiveSeeds")]
    partial class ExhaustiveSeeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProcessTracker.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3129),
                            Description = "Human Resources portal and management",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3130),
                            Title = "HR Management System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3132),
                            Description = "CRM application for sales and tracking",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3132),
                            Title = "Customer Relationship Management"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3134),
                            Description = "Internal accounting and billing portal",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3134),
                            Title = "Financial Accounting Portal"
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProcessDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CR",
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3234),
                            Description = "CR Process",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3234),
                            Name = "Change Request"
                        },
                        new
                        {
                            Id = 2,
                            Code = "INCIDENT",
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3237),
                            Description = "Incident Process",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3237),
                            Name = "Incident Management"
                        },
                        new
                        {
                            Id = 3,
                            Code = "UT",
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3239),
                            Description = "Unit Testing Process",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3239),
                            Name = "Unit Testing"
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Max")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<decimal?>("Min")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MinLength")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pattern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placeholder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDefinitionId");

                    b.ToTable("ProcessFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3260),
                            FieldName = "Title",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Change Title",
                            MaxLength = 255,
                            MinLength = 5,
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3261),
                            Placeholder = "Brief title",
                            ProcessDefinitionId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3263),
                            FieldName = "Description",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Detailed Description",
                            MinLength = 20,
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3264),
                            ProcessDefinitionId = 1,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3266),
                            FieldName = "Priority",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Priority Level",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3266),
                            OptionsJson = "[{\"label\":\"Critical\",\"value\":\"CRITICAL\"},{\"label\":\"High\",\"value\":\"HIGH\"},{\"label\":\"Medium\",\"value\":\"MEDIUM\"},{\"label\":\"Low\",\"value\":\"LOW\"}]",
                            ProcessDefinitionId = 1,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3268),
                            FieldName = "ChangeType",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Type of Change",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3268),
                            OptionsJson = "[{\"label\":\"Emergency\",\"value\":\"EMERGENCY\"},{\"label\":\"Urgent\",\"value\":\"URGENT\"},{\"label\":\"Standard\",\"value\":\"STANDARD\"},{\"label\":\"Minor\",\"value\":\"MINOR\"}]",
                            ProcessDefinitionId = 1,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3270),
                            FieldName = "ImpactScope",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Impact Scope",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3270),
                            ProcessDefinitionId = 1,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3272),
                            FieldName = "ImplementationDate",
                            FieldType = 2,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Implementation Date",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3272),
                            ProcessDefinitionId = 1,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3274),
                            FieldName = "RollbackPlan",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Rollback Plan",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3274),
                            ProcessDefinitionId = 1,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3276),
                            FieldName = "CRNumber",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "CR Number",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3276),
                            Placeholder = "e.g., CR-2024-001",
                            ProcessDefinitionId = 1,
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3317),
                            FieldName = "IncidentId",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Incident ID",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3318),
                            Placeholder = "e.g., INC-2024-001",
                            ProcessDefinitionId = 2,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3320),
                            FieldName = "Title",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Incident Title",
                            MaxLength = 255,
                            MinLength = 5,
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3320),
                            ProcessDefinitionId = 2,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3322),
                            FieldName = "Description",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Incident Description",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3322),
                            ProcessDefinitionId = 2,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3324),
                            FieldName = "Severity",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Severity Level",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3324),
                            OptionsJson = "[{\"label\":\"Blocker\",\"value\":\"BLOCKER\"},{\"label\":\"Critical\",\"value\":\"CRITICAL\"},{\"label\":\"Major\",\"value\":\"MAJOR\"},{\"label\":\"Minor\",\"value\":\"MINOR\"}]",
                            ProcessDefinitionId = 2,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3326),
                            FieldName = "ReportedDate",
                            FieldType = 3,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Date Reported",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3326),
                            ProcessDefinitionId = 2,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3333),
                            FieldName = "AffectedUsers",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Number of Affected Users",
                            Max = 10000m,
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3334),
                            ProcessDefinitionId = 2,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3335),
                            FieldName = "ResolutionNotes",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Resolution Notes",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3336),
                            ProcessDefinitionId = 2,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3352),
                            FieldName = "TestId",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Test ID",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3352),
                            Placeholder = "e.g., UT-2024-001",
                            ProcessDefinitionId = 3,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3354),
                            FieldName = "ModuleUnderTest",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Module Name",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3354),
                            Placeholder = "e.g., AuthService",
                            ProcessDefinitionId = 3,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3356),
                            FieldName = "TestCases",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Number of Test Cases",
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3357),
                            ProcessDefinitionId = 3,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3358),
                            FieldName = "PassedCases",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Passed Test Cases",
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3359),
                            ProcessDefinitionId = 3,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3361),
                            FieldName = "FailedCases",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Failed Test Cases",
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3361),
                            ProcessDefinitionId = 3,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3363),
                            FieldName = "CodeCoverage",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Code Coverage %",
                            Max = 100m,
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3364),
                            ProcessDefinitionId = 3,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3365),
                            FieldName = "TestStatus",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Overall Status",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3366),
                            OptionsJson = "[{\"label\":\"Passed\",\"value\":\"PASSED\"},{\"label\":\"Failed\",\"value\":\"FAILED\"},{\"label\":\"In Progress\",\"value\":\"IN_PROGRESS\"},{\"label\":\"Not Started\",\"value\":\"NOT_STARTED\"}]",
                            ProcessDefinitionId = 3,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3367),
                            FieldName = "Notes",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Test Notes",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3368),
                            ProcessDefinitionId = 3,
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpectedDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldValuesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("RecordNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ProcessDefinitionId");

                    b.ToTable("ProcessRecords");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApplicationId = 1,
                            AssignedTo = "john.doe@company.com",
                            CreatedDate = new DateTime(2026, 9, 6, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            ExpectedDueDate = new DateTime(2026, 9, 16, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            FieldValuesJson = "{\"Title\":\"Upgrade HR Portal Database\",\"Description\":\"Database needs to be migrated to the latest version for better performance.\",\"ChangeType\":\"STANDARD\",\"CRNumber\":\"CR-2024-001\"}",
                            ModifiedDate = new DateTime(2026, 9, 11, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            Priority = "HIGH",
                            ProcessDefinitionId = 1,
                            RecordNumber = "CR-2024-001",
                            RecordStatus = "Submitted",
                            SubmittedDate = new DateTime(2026, 9, 11, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374)
                        },
                        new
                        {
                            Id = 501L,
                            ApplicationId = 2,
                            AssignedTo = "jenna.devops@company.com",
                            CreatedDate = new DateTime(2026, 9, 19, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            ExpectedDueDate = new DateTime(2026, 9, 20, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            FieldValuesJson = "{\"Title\":\"CRM Login Gateway Down\",\"Description\":\"Customer logins are timing out on the central gateway.\",\"IncidentId\":\"INC-2024-001\",\"Severity\":\"CRITICAL\",\"AffectedUsers\":\"1500\",\"ResolutionNotes\":\"Rebooted instances\"}",
                            ModifiedDate = new DateTime(2026, 9, 20, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            Priority = "CRITICAL",
                            ProcessDefinitionId = 2,
                            RecordNumber = "INC-2024-001",
                            RecordStatus = "Submitted",
                            SubmittedDate = new DateTime(2026, 9, 20, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374)
                        },
                        new
                        {
                            Id = 502L,
                            ApplicationId = 2,
                            CreatedDate = new DateTime(2026, 9, 21, 10, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            ExpectedDueDate = new DateTime(2026, 9, 21, 22, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            FieldValuesJson = "{\"Title\":\"Payment Gateway Latency\",\"Description\":\"Payments are processing but taking up to 30 seconds.\",\"IncidentId\":\"INC-2024-002\",\"Severity\":\"MAJOR\",\"AffectedUsers\":\"250\"}",
                            ModifiedDate = new DateTime(2026, 9, 21, 18, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            Priority = "BLOCKER",
                            ProcessDefinitionId = 2,
                            RecordNumber = "INC-2024-002",
                            RecordStatus = "Draft"
                        },
                        new
                        {
                            Id = 503L,
                            ApplicationId = 3,
                            AssignedTo = "mark.qa@company.com",
                            CreatedDate = new DateTime(2026, 9, 20, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            ExpectedDueDate = new DateTime(2026, 9, 25, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            FieldValuesJson = "{\"TestId\":\"UT-2024-001\",\"ModuleUnderTest\":\"BillingCalculator\",\"TestCases\":\"45\",\"PassedCases\":\"44\",\"FailedCases\":\"1\",\"CodeCoverage\":\"85\",\"TestStatus\":\"FAILED\"}",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            Priority = "LOW",
                            ProcessDefinitionId = 3,
                            RecordNumber = "UT-2024-001",
                            RecordStatus = "Submitted",
                            SubmittedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374)
                        },
                        new
                        {
                            Id = 504L,
                            ApplicationId = 3,
                            AssignedTo = "jenna.devops@company.com",
                            CreatedDate = new DateTime(2026, 9, 18, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            ExpectedDueDate = new DateTime(2026, 9, 22, 1, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            FieldValuesJson = "{\"TestId\":\"UT-2024-002\",\"ModuleUnderTest\":\"AuthTokenService\",\"TestCases\":\"12\",\"PassedCases\":\"12\",\"FailedCases\":\"0\",\"CodeCoverage\":\"100\",\"TestStatus\":\"PASSED\"}",
                            ModifiedDate = new DateTime(2026, 9, 20, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            Priority = "MEDIUM",
                            ProcessDefinitionId = 3,
                            RecordNumber = "UT-2024-002",
                            RecordStatus = "Submitted",
                            SubmittedDate = new DateTime(2026, 9, 20, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374)
                        },
                        new
                        {
                            Id = 505L,
                            ApplicationId = 1,
                            CreatedDate = new DateTime(2026, 9, 20, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            ExpectedDueDate = new DateTime(2026, 9, 20, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            FieldValuesJson = "{\"Title\":\"Fix CSS Dropdown Glitch\",\"Description\":\"The dropdowns are hanging off the screen.\",\"ChangeType\":\"MINOR\",\"CRNumber\":\"CR-2024-002\"}",
                            ModifiedDate = new DateTime(2026, 9, 21, 15, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            Priority = "MEDIUM",
                            ProcessDefinitionId = 1,
                            RecordNumber = "CR-2024-002",
                            RecordStatus = "Draft"
                        },
                        new
                        {
                            Id = 506L,
                            ApplicationId = 2,
                            AssignedTo = "alex@ops.com",
                            CreatedDate = new DateTime(2026, 9, 21, 19, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            ExpectedDueDate = new DateTime(2026, 9, 22, 8, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            FieldValuesJson = "{\"Title\":\"High CPU on Redis API\",\"Description\":\"Nodes are spinning at 99% usage.\",\"IncidentId\":\"INC-2024-003\",\"Severity\":\"MAJOR\",\"AffectedUsers\":\"40\"}",
                            ModifiedDate = new DateTime(2026, 9, 21, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            Priority = "HIGH",
                            ProcessDefinitionId = 2,
                            RecordNumber = "INC-2024-003",
                            RecordStatus = "Draft"
                        },
                        new
                        {
                            Id = 507L,
                            ApplicationId = 1,
                            AssignedTo = "alex@ops.com",
                            CreatedDate = new DateTime(2026, 9, 16, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            ExpectedDueDate = new DateTime(2026, 9, 23, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            FieldValuesJson = "{\"Title\":\"Migrate Payment Gateway\",\"Description\":\"Shift entirely away from legacy API endpoints.\",\"ChangeType\":\"EMERGENCY\",\"CRNumber\":\"CR-2024-003\"}",
                            ModifiedDate = new DateTime(2026, 9, 17, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374),
                            Priority = "CRITICAL",
                            ProcessDefinitionId = 1,
                            RecordNumber = "CR-2024-003",
                            RecordStatus = "Submitted",
                            SubmittedDate = new DateTime(2026, 9, 17, 20, 28, 13, 444, DateTimeKind.Utc).AddTicks(3374)
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessField", b =>
                {
                    b.HasOne("ProcessTracker.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany("Fields")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessDefinition");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessRecord", b =>
                {
                    b.HasOne("ProcessTracker.Entities.Application", "Application")
                        .WithMany("ProcessRecords")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcessTracker.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany("Records")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("ProcessDefinition");
                });

            modelBuilder.Entity("ProcessTracker.Entities.Application", b =>
                {
                    b.Navigation("ProcessRecords");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessDefinition", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
