// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessTracker.Data;

#nullable disable

namespace ProcessTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260921054740_FlattenJSON")]
    partial class FlattenJSON
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProcessTracker.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9779),
                            Description = "Human Resources portal and management",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9781),
                            Title = "HR Management System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9783),
                            Description = "CRM application for sales and tracking",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9784),
                            Title = "Customer Relationship Management"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9785),
                            Description = "Internal accounting and billing portal",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9786),
                            Title = "Financial Accounting Portal"
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProcessDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CR",
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9920),
                            Description = "CR Process",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9920),
                            Name = "Change Request"
                        },
                        new
                        {
                            Id = 2,
                            Code = "INCIDENT",
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9922),
                            Description = "Incident Process",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9923),
                            Name = "Incident Management"
                        },
                        new
                        {
                            Id = 3,
                            Code = "UT",
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9925),
                            Description = "Unit Testing Process",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9925),
                            Name = "Unit Testing"
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Max")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<decimal?>("Min")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MinLength")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pattern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placeholder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDefinitionId");

                    b.ToTable("ProcessFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9945),
                            FieldName = "Title",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Change Title",
                            MaxLength = 255,
                            MinLength = 5,
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9946),
                            Placeholder = "Brief title",
                            ProcessDefinitionId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9948),
                            FieldName = "Description",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Detailed Description",
                            MinLength = 20,
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9949),
                            ProcessDefinitionId = 1,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9951),
                            FieldName = "Priority",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Priority Level",
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9951),
                            OptionsJson = "[{\"label\":\"Critical\",\"value\":\"CRITICAL\"},{\"label\":\"High\",\"value\":\"HIGH\"},{\"label\":\"Medium\",\"value\":\"MEDIUM\"},{\"label\":\"Low\",\"value\":\"LOW\"}]",
                            ProcessDefinitionId = 1,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9953),
                            FieldName = "ChangeType",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Type of Change",
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9953),
                            OptionsJson = "[{\"label\":\"Emergency\",\"value\":\"EMERGENCY\"},{\"label\":\"Urgent\",\"value\":\"URGENT\"},{\"label\":\"Standard\",\"value\":\"STANDARD\"},{\"label\":\"Minor\",\"value\":\"MINOR\"}]",
                            ProcessDefinitionId = 1,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9955),
                            FieldName = "ImpactScope",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Impact Scope",
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9955),
                            ProcessDefinitionId = 1,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9957),
                            FieldName = "ImplementationDate",
                            FieldType = 2,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Implementation Date",
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9957),
                            ProcessDefinitionId = 1,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9959),
                            FieldName = "RollbackPlan",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Rollback Plan",
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9959),
                            ProcessDefinitionId = 1,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9961),
                            FieldName = "CRNumber",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "CR Number",
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9961),
                            Placeholder = "e.g., CR-2024-001",
                            ProcessDefinitionId = 1,
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9978),
                            FieldName = "IncidentId",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Incident ID",
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9978),
                            Placeholder = "e.g., INC-2024-001",
                            ProcessDefinitionId = 2,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9980),
                            FieldName = "Title",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Incident Title",
                            MaxLength = 255,
                            MinLength = 5,
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9981),
                            ProcessDefinitionId = 2,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9983),
                            FieldName = "Description",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Incident Description",
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9983),
                            ProcessDefinitionId = 2,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9985),
                            FieldName = "Severity",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Severity Level",
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9985),
                            OptionsJson = "[{\"label\":\"Blocker\",\"value\":\"BLOCKER\"},{\"label\":\"Critical\",\"value\":\"CRITICAL\"},{\"label\":\"Major\",\"value\":\"MAJOR\"},{\"label\":\"Minor\",\"value\":\"MINOR\"}]",
                            ProcessDefinitionId = 2,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9987),
                            FieldName = "ReportedDate",
                            FieldType = 3,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Date Reported",
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9987),
                            ProcessDefinitionId = 2,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9994),
                            FieldName = "AffectedUsers",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Number of Affected Users",
                            Max = 10000m,
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9994),
                            ProcessDefinitionId = 2,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9996),
                            FieldName = "ResolutionNotes",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Resolution Notes",
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 862, DateTimeKind.Utc).AddTicks(9996),
                            ProcessDefinitionId = 2,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(12),
                            FieldName = "TestId",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Test ID",
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(13),
                            Placeholder = "e.g., UT-2024-001",
                            ProcessDefinitionId = 3,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(14),
                            FieldName = "ModuleUnderTest",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Module Name",
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(15),
                            Placeholder = "e.g., AuthService",
                            ProcessDefinitionId = 3,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(17),
                            FieldName = "TestCases",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Number of Test Cases",
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(17),
                            ProcessDefinitionId = 3,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(19),
                            FieldName = "PassedCases",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Passed Test Cases",
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(20),
                            ProcessDefinitionId = 3,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(21),
                            FieldName = "FailedCases",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Failed Test Cases",
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(22),
                            ProcessDefinitionId = 3,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(24),
                            FieldName = "CodeCoverage",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Code Coverage %",
                            Max = 100m,
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(25),
                            ProcessDefinitionId = 3,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(26),
                            FieldName = "TestStatus",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Overall Status",
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(27),
                            OptionsJson = "[{\"label\":\"Passed\",\"value\":\"PASSED\"},{\"label\":\"Failed\",\"value\":\"FAILED\"},{\"label\":\"In Progress\",\"value\":\"IN_PROGRESS\"},{\"label\":\"Not Started\",\"value\":\"NOT_STARTED\"}]",
                            ProcessDefinitionId = 3,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(28),
                            FieldName = "Notes",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Test Notes",
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(29),
                            ProcessDefinitionId = 3,
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldValuesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("RecordNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ProcessDefinitionId");

                    b.ToTable("ProcessRecords");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApplicationId = 1,
                            CreatedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(66),
                            FieldValuesJson = "{\"Title\":\"Upgrade HR Portal Database\",\"Description\":\"Database needs to be migrated to the latest version for better performance.\",\"Priority\":\"HIGH\",\"ChangeType\":\"STANDARD\",\"ImplementationDate\":\"2024-12-01\",\"CRNumber\":\"CR-2024-001\"}",
                            ModifiedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(66),
                            ProcessDefinitionId = 1,
                            RecordNumber = "CR-2024-001",
                            RecordStatus = "Submitted",
                            SubmittedDate = new DateTime(2026, 9, 21, 5, 47, 39, 863, DateTimeKind.Utc).AddTicks(67)
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessField", b =>
                {
                    b.HasOne("ProcessTracker.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany("Fields")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessDefinition");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessRecord", b =>
                {
                    b.HasOne("ProcessTracker.Entities.Application", "Application")
                        .WithMany("ProcessRecords")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcessTracker.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany("Records")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("ProcessDefinition");
                });

            modelBuilder.Entity("ProcessTracker.Entities.Application", b =>
                {
                    b.Navigation("ProcessRecords");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessDefinition", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
