// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessTracker.Data;

#nullable disable

namespace ProcessTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260921164640_HybridSystemFields2")]
    partial class HybridSystemFields2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProcessTracker.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1183),
                            Description = "Human Resources portal and management",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1184),
                            Title = "HR Management System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1186),
                            Description = "CRM application for sales and tracking",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1186),
                            Title = "Customer Relationship Management"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1188),
                            Description = "Internal accounting and billing portal",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1188),
                            Title = "Financial Accounting Portal"
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProcessDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CR",
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1297),
                            Description = "CR Process",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1298),
                            Name = "Change Request"
                        },
                        new
                        {
                            Id = 2,
                            Code = "INCIDENT",
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1300),
                            Description = "Incident Process",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1301),
                            Name = "Incident Management"
                        },
                        new
                        {
                            Id = 3,
                            Code = "UT",
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1302),
                            Description = "Unit Testing Process",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1303),
                            Name = "Unit Testing"
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Max")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<decimal?>("Min")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MinLength")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pattern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placeholder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDefinitionId");

                    b.ToTable("ProcessFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1329),
                            FieldName = "Title",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Change Title",
                            MaxLength = 255,
                            MinLength = 5,
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1329),
                            Placeholder = "Brief title",
                            ProcessDefinitionId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1332),
                            FieldName = "Description",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Detailed Description",
                            MinLength = 20,
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1332),
                            ProcessDefinitionId = 1,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1334),
                            FieldName = "Priority",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Priority Level",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1335),
                            OptionsJson = "[{\"label\":\"Critical\",\"value\":\"CRITICAL\"},{\"label\":\"High\",\"value\":\"HIGH\"},{\"label\":\"Medium\",\"value\":\"MEDIUM\"},{\"label\":\"Low\",\"value\":\"LOW\"}]",
                            ProcessDefinitionId = 1,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1336),
                            FieldName = "ChangeType",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Type of Change",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1337),
                            OptionsJson = "[{\"label\":\"Emergency\",\"value\":\"EMERGENCY\"},{\"label\":\"Urgent\",\"value\":\"URGENT\"},{\"label\":\"Standard\",\"value\":\"STANDARD\"},{\"label\":\"Minor\",\"value\":\"MINOR\"}]",
                            ProcessDefinitionId = 1,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1338),
                            FieldName = "ImpactScope",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Impact Scope",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1339),
                            ProcessDefinitionId = 1,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1378),
                            FieldName = "ImplementationDate",
                            FieldType = 2,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Implementation Date",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1378),
                            ProcessDefinitionId = 1,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1380),
                            FieldName = "RollbackPlan",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Rollback Plan",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1380),
                            ProcessDefinitionId = 1,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1382),
                            FieldName = "CRNumber",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "CR Number",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1383),
                            Placeholder = "e.g., CR-2024-001",
                            ProcessDefinitionId = 1,
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1400),
                            FieldName = "IncidentId",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Incident ID",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1400),
                            Placeholder = "e.g., INC-2024-001",
                            ProcessDefinitionId = 2,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1402),
                            FieldName = "Title",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Incident Title",
                            MaxLength = 255,
                            MinLength = 5,
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1403),
                            ProcessDefinitionId = 2,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1404),
                            FieldName = "Description",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Incident Description",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1405),
                            ProcessDefinitionId = 2,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1406),
                            FieldName = "Severity",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Severity Level",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1407),
                            OptionsJson = "[{\"label\":\"Blocker\",\"value\":\"BLOCKER\"},{\"label\":\"Critical\",\"value\":\"CRITICAL\"},{\"label\":\"Major\",\"value\":\"MAJOR\"},{\"label\":\"Minor\",\"value\":\"MINOR\"}]",
                            ProcessDefinitionId = 2,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1408),
                            FieldName = "ReportedDate",
                            FieldType = 3,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Date Reported",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1409),
                            ProcessDefinitionId = 2,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1417),
                            FieldName = "AffectedUsers",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Number of Affected Users",
                            Max = 10000m,
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1418),
                            ProcessDefinitionId = 2,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1419),
                            FieldName = "ResolutionNotes",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Resolution Notes",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1420),
                            ProcessDefinitionId = 2,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1435),
                            FieldName = "TestId",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Test ID",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1435),
                            Placeholder = "e.g., UT-2024-001",
                            ProcessDefinitionId = 3,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1437),
                            FieldName = "ModuleUnderTest",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Module Name",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1437),
                            Placeholder = "e.g., AuthService",
                            ProcessDefinitionId = 3,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1439),
                            FieldName = "TestCases",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Number of Test Cases",
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1439),
                            ProcessDefinitionId = 3,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1441),
                            FieldName = "PassedCases",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Passed Test Cases",
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1442),
                            ProcessDefinitionId = 3,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1444),
                            FieldName = "FailedCases",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Failed Test Cases",
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1444),
                            ProcessDefinitionId = 3,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1446),
                            FieldName = "CodeCoverage",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Code Coverage %",
                            Max = 100m,
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1447),
                            ProcessDefinitionId = 3,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1448),
                            FieldName = "TestStatus",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Overall Status",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1449),
                            OptionsJson = "[{\"label\":\"Passed\",\"value\":\"PASSED\"},{\"label\":\"Failed\",\"value\":\"FAILED\"},{\"label\":\"In Progress\",\"value\":\"IN_PROGRESS\"},{\"label\":\"Not Started\",\"value\":\"NOT_STARTED\"}]",
                            ProcessDefinitionId = 3,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1450),
                            FieldName = "Notes",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Test Notes",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1450),
                            ProcessDefinitionId = 3,
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpectedDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldValuesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("RecordNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ProcessDefinitionId");

                    b.ToTable("ProcessRecords");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApplicationId = 1,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1469),
                            FieldValuesJson = "{\"Title\":\"Upgrade HR Portal Database\",\"Description\":\"Database needs to be migrated to the latest version for better performance.\",\"Priority\":\"HIGH\",\"ChangeType\":\"STANDARD\",\"ImplementationDate\":\"2024-12-01\",\"CRNumber\":\"CR-2024-001\"}",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1470),
                            ProcessDefinitionId = 1,
                            RecordNumber = "CR-2024-001",
                            RecordStatus = "Submitted",
                            SubmittedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1470)
                        },
                        new
                        {
                            Id = 101L,
                            ApplicationId = 2,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1475),
                            FieldValuesJson = "{\"Title\":\"CRM Login Gateway Down\",\"Description\":\"Customer logins are timing out on the central gateway.\",\"IncidentId\":\"INC-2024-001\",\"Severity\":\"CRITICAL\",\"ReportedDate\":\"2024-09-20T10:00:00Z\",\"AffectedUsers\":\"1500\",\"ResolutionNotes\":\"Rebooted instances\"}",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1475),
                            ProcessDefinitionId = 2,
                            RecordNumber = "INC-2024-001",
                            RecordStatus = "Submitted",
                            SubmittedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1476)
                        },
                        new
                        {
                            Id = 102L,
                            ApplicationId = 2,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1478),
                            FieldValuesJson = "{\"Title\":\"Payment Gateway Latency\",\"Description\":\"Payments are processing but taking up to 30 seconds.\",\"IncidentId\":\"INC-2024-002\",\"Severity\":\"MAJOR\",\"ReportedDate\":\"2024-09-21T08:30:00Z\",\"AffectedUsers\":\"250\"}",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1478),
                            ProcessDefinitionId = 2,
                            RecordNumber = "INC-2024-002",
                            RecordStatus = "Draft"
                        },
                        new
                        {
                            Id = 103L,
                            ApplicationId = 3,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1480),
                            FieldValuesJson = "{\"TestId\":\"UT-2024-001\",\"ModuleUnderTest\":\"BillingCalculator\",\"TestCases\":\"45\",\"PassedCases\":\"44\",\"FailedCases\":\"1\",\"CodeCoverage\":\"85\",\"TestStatus\":\"FAILED\",\"Notes\":\"Failing isolated edge case on leap year billing calculation.\"}",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1480),
                            ProcessDefinitionId = 3,
                            RecordNumber = "UT-2024-001",
                            RecordStatus = "Submitted",
                            SubmittedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1480)
                        },
                        new
                        {
                            Id = 104L,
                            ApplicationId = 3,
                            CreatedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1482),
                            FieldValuesJson = "{\"TestId\":\"UT-2024-002\",\"ModuleUnderTest\":\"AuthTokenService\",\"TestCases\":\"12\",\"PassedCases\":\"12\",\"FailedCases\":\"0\",\"CodeCoverage\":\"100\",\"TestStatus\":\"PASSED\",\"Notes\":\"Fully verified standard configurations.\"}",
                            ModifiedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1482),
                            ProcessDefinitionId = 3,
                            RecordNumber = "UT-2024-002",
                            RecordStatus = "Submitted",
                            SubmittedDate = new DateTime(2026, 9, 21, 16, 46, 39, 904, DateTimeKind.Utc).AddTicks(1483)
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessField", b =>
                {
                    b.HasOne("ProcessTracker.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany("Fields")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessDefinition");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessRecord", b =>
                {
                    b.HasOne("ProcessTracker.Entities.Application", "Application")
                        .WithMany("ProcessRecords")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcessTracker.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany("Records")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("ProcessDefinition");
                });

            modelBuilder.Entity("ProcessTracker.Entities.Application", b =>
                {
                    b.Navigation("ProcessRecords");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessDefinition", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
