// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessTracker.Data;

#nullable disable

namespace ProcessTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260919130546_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProcessTracker.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(2958),
                            Description = "Process for managing change requests",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(2961),
                            Title = "Change Request"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(2963),
                            Description = "Process for reporting and tracking incidents",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(2964),
                            Title = "Incident Management"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(2965),
                            Description = "Process for unit testing documentation",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(2966),
                            Title = "Unit Testing"
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProcessDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CR",
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3147),
                            Description = "CR Process",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3148),
                            Name = "Change Request"
                        },
                        new
                        {
                            Id = 2,
                            Code = "INCIDENT",
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3150),
                            Description = "Incident Process",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3151),
                            Name = "Incident Management"
                        },
                        new
                        {
                            Id = 3,
                            Code = "UT",
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3153),
                            Description = "Unit Testing Process",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3153),
                            Name = "Unit Testing"
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Max")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<decimal?>("Min")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MinLength")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pattern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placeholder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDefinitionId");

                    b.ToTable("ProcessFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3179),
                            FieldName = "Title",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Change Title",
                            MaxLength = 255,
                            MinLength = 5,
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3181),
                            Placeholder = "Brief title",
                            ProcessDefinitionId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3185),
                            FieldName = "Description",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Detailed Description",
                            MinLength = 20,
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3186),
                            ProcessDefinitionId = 1,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3188),
                            FieldName = "Priority",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Priority Level",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3189),
                            OptionsJson = "[{\"label\":\"Critical\",\"value\":\"CRITICAL\"},{\"label\":\"High\",\"value\":\"HIGH\"},{\"label\":\"Medium\",\"value\":\"MEDIUM\"},{\"label\":\"Low\",\"value\":\"LOW\"}]",
                            ProcessDefinitionId = 1,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3191),
                            FieldName = "ChangeType",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Type of Change",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3192),
                            OptionsJson = "[{\"label\":\"Emergency\",\"value\":\"EMERGENCY\"},{\"label\":\"Urgent\",\"value\":\"URGENT\"},{\"label\":\"Standard\",\"value\":\"STANDARD\"},{\"label\":\"Minor\",\"value\":\"MINOR\"}]",
                            ProcessDefinitionId = 1,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3194),
                            FieldName = "ImpactScope",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Impact Scope",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3194),
                            ProcessDefinitionId = 1,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3196),
                            FieldName = "ImplementationDate",
                            FieldType = 2,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Implementation Date",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3197),
                            ProcessDefinitionId = 1,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3199),
                            FieldName = "RollbackPlan",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Rollback Plan",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3200),
                            ProcessDefinitionId = 1,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3202),
                            FieldName = "CRNumber",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "CR Number",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3203),
                            Placeholder = "e.g., CR-2024-001",
                            ProcessDefinitionId = 1,
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3225),
                            FieldName = "IncidentId",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Incident ID",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3226),
                            Placeholder = "e.g., INC-2024-001",
                            ProcessDefinitionId = 2,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3228),
                            FieldName = "Title",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Incident Title",
                            MaxLength = 255,
                            MinLength = 5,
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3229),
                            ProcessDefinitionId = 2,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3231),
                            FieldName = "Description",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Incident Description",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3231),
                            ProcessDefinitionId = 2,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3233),
                            FieldName = "Severity",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Severity Level",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3234),
                            OptionsJson = "[{\"label\":\"Blocker\",\"value\":\"BLOCKER\"},{\"label\":\"Critical\",\"value\":\"CRITICAL\"},{\"label\":\"Major\",\"value\":\"MAJOR\"},{\"label\":\"Minor\",\"value\":\"MINOR\"}]",
                            ProcessDefinitionId = 2,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3236),
                            FieldName = "ReportedDate",
                            FieldType = 3,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Date Reported",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3237),
                            ProcessDefinitionId = 2,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3244),
                            FieldName = "AffectedUsers",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Number of Affected Users",
                            Max = 10000m,
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3245),
                            ProcessDefinitionId = 2,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3247),
                            FieldName = "ResolutionNotes",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Resolution Notes",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3247),
                            ProcessDefinitionId = 2,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3319),
                            FieldName = "TestId",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Test ID",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3320),
                            Placeholder = "e.g., UT-2024-001",
                            ProcessDefinitionId = 3,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3322),
                            FieldName = "ModuleUnderTest",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Module Name",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3323),
                            Placeholder = "e.g., AuthService",
                            ProcessDefinitionId = 3,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3325),
                            FieldName = "TestCases",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Number of Test Cases",
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3326),
                            ProcessDefinitionId = 3,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3328),
                            FieldName = "PassedCases",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Passed Test Cases",
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3328),
                            ProcessDefinitionId = 3,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3331),
                            FieldName = "FailedCases",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Failed Test Cases",
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3331),
                            ProcessDefinitionId = 3,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3334),
                            FieldName = "CodeCoverage",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Code Coverage %",
                            Max = 100m,
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3334),
                            ProcessDefinitionId = 3,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3336),
                            FieldName = "TestStatus",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Overall Status",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3337),
                            OptionsJson = "[{\"label\":\"Passed\",\"value\":\"PASSED\"},{\"label\":\"Failed\",\"value\":\"FAILED\"},{\"label\":\"In Progress\",\"value\":\"IN_PROGRESS\"},{\"label\":\"Not Started\",\"value\":\"NOT_STARTED\"}]",
                            ProcessDefinitionId = 3,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3339),
                            FieldName = "Notes",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Test Notes",
                            ModifiedDate = new DateTime(2026, 9, 19, 13, 5, 46, 239, DateTimeKind.Utc).AddTicks(3339),
                            ProcessDefinitionId = 3,
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("RecordNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ProcessDefinitionId");

                    b.ToTable("ProcessRecords");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessRecordFieldValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProcessFieldId")
                        .HasColumnType("int");

                    b.Property<long>("ProcessRecordId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProcessFieldId");

                    b.HasIndex("ProcessRecordId");

                    b.ToTable("ProcessRecordFieldValues");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessField", b =>
                {
                    b.HasOne("ProcessTracker.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany("Fields")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessDefinition");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessRecord", b =>
                {
                    b.HasOne("ProcessTracker.Entities.Application", "Application")
                        .WithMany("ProcessRecords")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcessTracker.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany("Records")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("ProcessDefinition");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessRecordFieldValue", b =>
                {
                    b.HasOne("ProcessTracker.Entities.ProcessField", "ProcessField")
                        .WithMany("FieldValues")
                        .HasForeignKey("ProcessFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcessTracker.Entities.ProcessRecord", "ProcessRecord")
                        .WithMany("FieldValues")
                        .HasForeignKey("ProcessRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessField");

                    b.Navigation("ProcessRecord");
                });

            modelBuilder.Entity("ProcessTracker.Entities.Application", b =>
                {
                    b.Navigation("ProcessRecords");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessDefinition", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Records");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessField", b =>
                {
                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessRecord", b =>
                {
                    b.Navigation("FieldValues");
                });
#pragma warning restore 612, 618
        }
    }
}
