// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProcessTracker.Data;

#nullable disable

namespace ProcessTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260920193748_AddFieldValuesIndexes")]
    partial class AddFieldValuesIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProcessTracker.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2137),
                            Description = "Human Resources portal and management",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2138),
                            Title = "HR Management System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2140),
                            Description = "CRM application for sales and tracking",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2141),
                            Title = "Customer Relationship Management"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2142),
                            Description = "Internal accounting and billing portal",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2142),
                            Title = "Financial Accounting Portal"
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProcessDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CR",
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2222),
                            Description = "CR Process",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2223),
                            Name = "Change Request"
                        },
                        new
                        {
                            Id = 2,
                            Code = "INCIDENT",
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2225),
                            Description = "Incident Process",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2225),
                            Name = "Incident Management"
                        },
                        new
                        {
                            Id = 3,
                            Code = "UT",
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2227),
                            Description = "Unit Testing Process",
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2227),
                            Name = "Unit Testing"
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Max")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<decimal?>("Min")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MinLength")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pattern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placeholder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessDefinitionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDefinitionId");

                    b.ToTable("ProcessFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2248),
                            FieldName = "Title",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Change Title",
                            MaxLength = 255,
                            MinLength = 5,
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2248),
                            Placeholder = "Brief title",
                            ProcessDefinitionId = 1,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2251),
                            FieldName = "Description",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Detailed Description",
                            MinLength = 20,
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2252),
                            ProcessDefinitionId = 1,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2254),
                            FieldName = "Priority",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Priority Level",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2254),
                            OptionsJson = "[{\"label\":\"Critical\",\"value\":\"CRITICAL\"},{\"label\":\"High\",\"value\":\"HIGH\"},{\"label\":\"Medium\",\"value\":\"MEDIUM\"},{\"label\":\"Low\",\"value\":\"LOW\"}]",
                            ProcessDefinitionId = 1,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2256),
                            FieldName = "ChangeType",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Type of Change",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2257),
                            OptionsJson = "[{\"label\":\"Emergency\",\"value\":\"EMERGENCY\"},{\"label\":\"Urgent\",\"value\":\"URGENT\"},{\"label\":\"Standard\",\"value\":\"STANDARD\"},{\"label\":\"Minor\",\"value\":\"MINOR\"}]",
                            ProcessDefinitionId = 1,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2258),
                            FieldName = "ImpactScope",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Impact Scope",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2259),
                            ProcessDefinitionId = 1,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2261),
                            FieldName = "ImplementationDate",
                            FieldType = 2,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Implementation Date",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2262),
                            ProcessDefinitionId = 1,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2263),
                            FieldName = "RollbackPlan",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Rollback Plan",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2264),
                            ProcessDefinitionId = 1,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2265),
                            FieldName = "CRNumber",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "CR Number",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2266),
                            Placeholder = "e.g., CR-2024-001",
                            ProcessDefinitionId = 1,
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2283),
                            FieldName = "IncidentId",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Incident ID",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2284),
                            Placeholder = "e.g., INC-2024-001",
                            ProcessDefinitionId = 2,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2286),
                            FieldName = "Title",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Incident Title",
                            MaxLength = 255,
                            MinLength = 5,
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2286),
                            ProcessDefinitionId = 2,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2288),
                            FieldName = "Description",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Incident Description",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2288),
                            ProcessDefinitionId = 2,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2290),
                            FieldName = "Severity",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Severity Level",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2290),
                            OptionsJson = "[{\"label\":\"Blocker\",\"value\":\"BLOCKER\"},{\"label\":\"Critical\",\"value\":\"CRITICAL\"},{\"label\":\"Major\",\"value\":\"MAJOR\"},{\"label\":\"Minor\",\"value\":\"MINOR\"}]",
                            ProcessDefinitionId = 2,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2292),
                            FieldName = "ReportedDate",
                            FieldType = 3,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Date Reported",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2292),
                            ProcessDefinitionId = 2,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2298),
                            FieldName = "AffectedUsers",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Number of Affected Users",
                            Max = 10000m,
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2298),
                            ProcessDefinitionId = 2,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2300),
                            FieldName = "ResolutionNotes",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Resolution Notes",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2300),
                            ProcessDefinitionId = 2,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2316),
                            FieldName = "TestId",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Test ID",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2317),
                            Placeholder = "e.g., UT-2024-001",
                            ProcessDefinitionId = 3,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2318),
                            FieldName = "ModuleUnderTest",
                            FieldType = 0,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Module Name",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2319),
                            Placeholder = "e.g., AuthService",
                            ProcessDefinitionId = 3,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2321),
                            FieldName = "TestCases",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Number of Test Cases",
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2321),
                            ProcessDefinitionId = 3,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2323),
                            FieldName = "PassedCases",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Passed Test Cases",
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2323),
                            ProcessDefinitionId = 3,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2325),
                            FieldName = "FailedCases",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Failed Test Cases",
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2325),
                            ProcessDefinitionId = 3,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2328),
                            FieldName = "CodeCoverage",
                            FieldType = 1,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Code Coverage %",
                            Max = 100m,
                            Min = 0m,
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2328),
                            ProcessDefinitionId = 3,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2330),
                            FieldName = "TestStatus",
                            FieldType = 4,
                            IsActive = true,
                            IsRequired = true,
                            Label = "Overall Status",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2330),
                            OptionsJson = "[{\"label\":\"Passed\",\"value\":\"PASSED\"},{\"label\":\"Failed\",\"value\":\"FAILED\"},{\"label\":\"In Progress\",\"value\":\"IN_PROGRESS\"},{\"label\":\"Not Started\",\"value\":\"NOT_STARTED\"}]",
                            ProcessDefinitionId = 3,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2332),
                            FieldName = "Notes",
                            FieldType = 5,
                            IsActive = true,
                            IsRequired = false,
                            Label = "Test Notes",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2332),
                            ProcessDefinitionId = 3,
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("RecordNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ProcessDefinitionId");

                    b.ToTable("ProcessRecords");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApplicationId = 1,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2405),
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2405),
                            ProcessDefinitionId = 1,
                            RecordNumber = "CR-2024-001",
                            RecordStatus = "Submitted",
                            SubmittedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2406)
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessRecordFieldValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProcessFieldId")
                        .HasColumnType("int");

                    b.Property<long>("ProcessRecordId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProcessFieldId")
                        .HasDatabaseName("IX_ProcessRecordFieldValues_ProcessFieldId_Include_FieldValue");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ProcessFieldId"), new[] { "FieldValue" });

                    b.HasIndex("ProcessRecordId", "ProcessFieldId")
                        .HasDatabaseName("IX_ProcessRecordFieldValues_Record_Field");

                    b.ToTable("ProcessRecordFieldValues");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2423),
                            FieldValue = "Upgrade HR Portal Database",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2424),
                            ProcessFieldId = 1,
                            ProcessRecordId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2425),
                            FieldValue = "Database needs to be migrated to the latest version for better performance.",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2426),
                            ProcessFieldId = 2,
                            ProcessRecordId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2427),
                            FieldValue = "HIGH",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2427),
                            ProcessFieldId = 3,
                            ProcessRecordId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2428),
                            FieldValue = "STANDARD",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2428),
                            ProcessFieldId = 4,
                            ProcessRecordId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2429),
                            FieldValue = "2024-12-01",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2430),
                            ProcessFieldId = 6,
                            ProcessRecordId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2431),
                            FieldValue = "CR-2024-001",
                            ModifiedDate = new DateTime(2026, 9, 20, 19, 37, 47, 843, DateTimeKind.Utc).AddTicks(2431),
                            ProcessFieldId = 8,
                            ProcessRecordId = 1L
                        });
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessField", b =>
                {
                    b.HasOne("ProcessTracker.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany("Fields")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessDefinition");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessRecord", b =>
                {
                    b.HasOne("ProcessTracker.Entities.Application", "Application")
                        .WithMany("ProcessRecords")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcessTracker.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany("Records")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("ProcessDefinition");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessRecordFieldValue", b =>
                {
                    b.HasOne("ProcessTracker.Entities.ProcessField", "ProcessField")
                        .WithMany("FieldValues")
                        .HasForeignKey("ProcessFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProcessTracker.Entities.ProcessRecord", "ProcessRecord")
                        .WithMany("FieldValues")
                        .HasForeignKey("ProcessRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessField");

                    b.Navigation("ProcessRecord");
                });

            modelBuilder.Entity("ProcessTracker.Entities.Application", b =>
                {
                    b.Navigation("ProcessRecords");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessDefinition", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Records");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessField", b =>
                {
                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("ProcessTracker.Entities.ProcessRecord", b =>
                {
                    b.Navigation("FieldValues");
                });
#pragma warning restore 612, 618
        }
    }
}
